swagger: '2.0'
info:
  version: '1.0.0'
  title: 'Product Service API'
paths:
  /products:
    get:
      summary: 'Get all products'
      responses:
        '200':
          description: 'Successful operation'
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/Product'
        '500':
          description: 'Internal server error'
  /products/{id}:
    get:
      summary: 'Get a specific product by its ID'
      parameters:
        - in: 'path'
          name: 'id'
          required: true
          type: 'string'
          description: 'ID of the product to fetch'
      responses:
        '200':
          description: 'Successful operation'
          schema:
            $ref: '#/definitions/Product'
        '400':
          description: 'Invalid ID provided'
        '404':
          description: 'Product not found'
        '500':
          description: 'Internal server error'
definitions:
  Product:
    type: 'object'
    properties:
      id:
        type: 'string'
      name:
        type: 'string'
      price:
        type: 'number'
      description:
        type: 'string'